#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 22, 2021 05:43:08 PM +07  platform: Windows NT

import sys

from PIL import Image, ImageTk
from tkinter import filedialog as fd, messagebox as mb
import pyttsx3
import pyttsx3.drivers.sapi5
import PyPDF2
import threading
import os
from os import path

try:
	import Tkinter as tk
except ImportError:
	import tkinter as tk

try:
	import ttk
	py3 = False
except ImportError:
	import tkinter.ttk as ttk
	py3 = True

import SachNoi_GUI_support

def vp_start_gui():
	'''Starting point when module is the main routine.'''
	global val, w, root
	root = tk.Tk()
	SachNoi_GUI_support.set_Tk_var()
	top = window (root)
	SachNoi_GUI_support.init(root, top)
	root.mainloop()

w = None
def create_window(rt, *args, **kwargs):
	'''Starting point when module is imported by another module.
	   Correct form of call: 'create_window(root, *args, **kwargs)' .'''
	global w, w_win, root
	#rt = root
	root = rt
	w = tk.Toplevel (root)
	SachNoi_GUI_support.set_Tk_var()
	top = window (w)
	SachNoi_GUI_support.init(w, top, *args, **kwargs)
	return (w, top)

def destroy_window():
	global w
	w.destroy()
	w = None

class window:
	def __init__(self, top=None):
		'''This class configures and populates the toplevel window.
		   top is the toplevel containing window.'''
		_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
		_fgcolor = '#000000'  # X11 color: 'black'
		_compcolor = '#d9d9d9' # X11 color: 'gray85'
		_ana1color = '#d9d9d9' # X11 color: 'gray85'
		_ana2color = '#ececec' # Closest X11 color: 'gray92'
		self.style = ttk.Style()
		if sys.platform == "win32":
			self.style.theme_use('winnative')
		self.style.configure('.',background=_bgcolor)
		self.style.configure('.',foreground=_fgcolor)
		self.style.configure('.',font="TkDefaultFont")
		self.style.map('.',background=
			[('selected', _compcolor), ('active',_ana2color)])

		top.geometry("575x692+485+40")
		top.minsize(120, 1)
		top.maxsize(1540, 845)
		top.resizable(1,  1)
		top.title("Sách nói")
		top.configure(background="#d9d9d9")
		top.configure(highlightbackground="#d9d9d9")
		top.configure(highlightcolor="black")

		self.lfReadMode = tk.LabelFrame(top)
		self.lfReadMode.place(relx=0.035, rely=0.246, relheight=0.413
				, relwidth=0.922)
		self.lfReadMode.configure(relief='groove')
		self.lfReadMode.configure(foreground="black")
		self.lfReadMode.configure(text='''Chế độ đọc''')
		self.lfReadMode.configure(background="#d9d9d9")
		self.lfReadMode.configure(highlightbackground="#d9d9d9")
		self.lfReadMode.configure(highlightcolor="black")

		self.Frame1 = tk.Frame(self.lfReadMode)
		self.Frame1.place(relx=0.038, rely=0.21, relheight=0.297, relwidth=0.726
				, bordermode='ignore')
		self.Frame1.configure(relief='groove')
		self.Frame1.configure(borderwidth="2")
		self.Frame1.configure(relief="groove")
		self.Frame1.configure(background="#d9d9d9")
		self.Frame1.configure(highlightbackground="#d9d9d9")
		self.Frame1.configure(highlightcolor="black")

		self.rbtReadOnePage = tk.Radiobutton(self.Frame1)
		self.rbtReadOnePage.place(relx=0.026, rely=0.118, relheight=0.294
				, relwidth=0.281)
		self.rbtReadOnePage.configure(activebackground="#ececec")
		self.rbtReadOnePage.configure(activeforeground="#000000")
		self.rbtReadOnePage.configure(background="#d9d9d9")
		self.rbtReadOnePage.configure(disabledforeground="#a3a3a3")
		self.rbtReadOnePage.configure(foreground="#000000")
		self.rbtReadOnePage.configure(highlightbackground="#d9d9d9")
		self.rbtReadOnePage.configure(highlightcolor="black")
		self.rbtReadOnePage.configure(justify='left')
		self.rbtReadOnePage.configure(text='''Đọc một trang:''')
		self.rbtReadOnePage.configure(value=1)
		self.rbtReadOnePage.configure(variable=SachNoi_GUI_support.selectedMode)

		self.lbSoTrang = tk.Label(self.Frame1)
		self.lbSoTrang.place(relx=0.078, rely=0.471, height=21, width=53)
		self.lbSoTrang.configure(activebackground="#f9f9f9")
		self.lbSoTrang.configure(activeforeground="black")
		self.lbSoTrang.configure(background="#d9d9d9")
		self.lbSoTrang.configure(disabledforeground="#a3a3a3")
		self.lbSoTrang.configure(foreground="#000000")
		self.lbSoTrang.configure(highlightbackground="#d9d9d9")
		self.lbSoTrang.configure(highlightcolor="black")
		self.lbSoTrang.configure(text='''Số trang:''')

		self.cbOnePage = ttk.Combobox(self.Frame1)
		self.cbOnePage.place(relx=0.234, rely=0.471, relheight=0.247
				, relwidth=0.216)
		self.cbOnePage.configure(textvariable=SachNoi_GUI_support.var_cbOnePage)
		self.cbOnePage.configure(takefocus="")

		self.Frame2 = tk.Frame(self.lfReadMode)
		self.Frame2.place(relx=0.038, rely=0.559, relheight=0.367, relwidth=0.726
				, bordermode='ignore')
		self.Frame2.configure(relief='groove')
		self.Frame2.configure(borderwidth="2")
		self.Frame2.configure(relief="groove")
		self.Frame2.configure(background="#d9d9d9")
		self.Frame2.configure(highlightbackground="#d9d9d9")
		self.Frame2.configure(highlightcolor="black")

		self.rbtReadMultiPages = tk.Radiobutton(self.Frame2)
		self.rbtReadMultiPages.place(relx=0.026, rely=0.095, relheight=0.238
				, relwidth=0.301)
		self.rbtReadMultiPages.configure(activebackground="#ececec")
		self.rbtReadMultiPages.configure(activeforeground="#000000")
		self.rbtReadMultiPages.configure(background="#d9d9d9")
		self.rbtReadMultiPages.configure(disabledforeground="#a3a3a3")
		self.rbtReadMultiPages.configure(foreground="#000000")
		self.rbtReadMultiPages.configure(highlightbackground="#d9d9d9")
		self.rbtReadMultiPages.configure(highlightcolor="black")
		self.rbtReadMultiPages.configure(justify='left')
		self.rbtReadMultiPages.configure(text='''Đọc nhiều trang:''')
		self.rbtReadMultiPages.configure(value=2)
		self.rbtReadMultiPages.configure(variable=SachNoi_GUI_support.selectedMode)

		self.lbTuTrang = tk.Label(self.Frame2)
		self.lbTuTrang.place(relx=0.078, rely=0.476, height=21, width=53)
		self.lbTuTrang.configure(activebackground="#f9f9f9")
		self.lbTuTrang.configure(activeforeground="black")
		self.lbTuTrang.configure(background="#d9d9d9")
		self.lbTuTrang.configure(disabledforeground="#a3a3a3")
		self.lbTuTrang.configure(foreground="#000000")
		self.lbTuTrang.configure(highlightbackground="#d9d9d9")
		self.lbTuTrang.configure(highlightcolor="black")
		self.lbTuTrang.configure(text='''Từ trang:''')

		self.cbMultiPagesFrom = ttk.Combobox(self.Frame2)
		self.cbMultiPagesFrom.place(relx=0.234, rely=0.476, relheight=0.2
				, relwidth=0.216)
		self.cbMultiPagesFrom.configure(textvariable=SachNoi_GUI_support.var_cbMultiPagesFrom)
		self.cbMultiPagesFrom.configure(takefocus="")

		self.lbDenTrang = tk.Label(self.Frame2)
		self.lbDenTrang.place(relx=0.545, rely=0.476, height=21, width=53)
		self.lbDenTrang.configure(activebackground="#f9f9f9")
		self.lbDenTrang.configure(activeforeground="black")
		self.lbDenTrang.configure(background="#d9d9d9")
		self.lbDenTrang.configure(disabledforeground="#a3a3a3")
		self.lbDenTrang.configure(foreground="#000000")
		self.lbDenTrang.configure(highlightbackground="#d9d9d9")
		self.lbDenTrang.configure(highlightcolor="black")
		self.lbDenTrang.configure(text='''Đến trang:''')

		self.cbMultiPagesTo = ttk.Combobox(self.Frame2)
		self.cbMultiPagesTo.place(relx=0.701, rely=0.476, relheight=0.2
				, relwidth=0.216)
		self.cbMultiPagesTo.configure(textvariable=SachNoi_GUI_support.var_cbMultiPagesTo)
		self.cbMultiPagesTo.configure(takefocus="")

		self.rbtReadAll = tk.Radiobutton(self.lfReadMode)
		self.rbtReadAll.place(relx=0.057, rely=0.07, relheight=0.087
				, relwidth=0.153, bordermode='ignore')
		self.rbtReadAll.configure(activebackground="#ececec")
		self.rbtReadAll.configure(activeforeground="#000000")
		self.rbtReadAll.configure(background="#d9d9d9")
		self.rbtReadAll.configure(disabledforeground="#a3a3a3")
		self.rbtReadAll.configure(foreground="#000000")
		self.rbtReadAll.configure(highlightbackground="#d9d9d9")
		self.rbtReadAll.configure(highlightcolor="black")
		self.rbtReadAll.configure(justify='left')
		self.rbtReadAll.configure(text='''Đọc tất cả''')
		self.rbtReadAll.configure(value=0)
		self.rbtReadAll.configure(variable=SachNoi_GUI_support.selectedMode)

		self.lbPicture2 = tk.Label(self.lfReadMode)
		self.lbPicture2.place(relx=0.811, rely=0.245, height=61, width=64
				, bordermode='ignore')
		self.lbPicture2.configure(activebackground="#f9f9f9")
		self.lbPicture2.configure(activeforeground="black")
		self.lbPicture2.configure(background="#80ff00")
		self.lbPicture2.configure(disabledforeground="#a3a3a3")
		self.lbPicture2.configure(foreground="#000000")
		self.lbPicture2.configure(highlightbackground="#d9d9d9")
		self.lbPicture2.configure(highlightcolor="black")

		self.lbPicture3 = tk.Label(self.lfReadMode)
		self.lbPicture3.place(relx=0.811, rely=0.629, height=61, width=64
				, bordermode='ignore')
		self.lbPicture3.configure(activebackground="#f9f9f9")
		self.lbPicture3.configure(activeforeground="black")
		self.lbPicture3.configure(background="#80ff00")
		self.lbPicture3.configure(disabledforeground="#a3a3a3")
		self.lbPicture3.configure(foreground="#000000")
		self.lbPicture3.configure(highlightbackground="#d9d9d9")
		self.lbPicture3.configure(highlightcolor="black")

		self.lfChooseBook = tk.LabelFrame(top)
		self.lfChooseBook.place(relx=0.035, rely=0.014, relheight=0.217
				, relwidth=0.925)
		self.lfChooseBook.configure(relief='groove')
		self.lfChooseBook.configure(foreground="black")
		self.lfChooseBook.configure(text='''Chọn sách''')
		self.lfChooseBook.configure(background="#d9d9d9")
		self.lfChooseBook.configure(highlightbackground="#d9d9d9")
		self.lfChooseBook.configure(highlightcolor="black")

		self.txtPdfPath = tk.Text(self.lfChooseBook)
		self.txtPdfPath.place(relx=0.207, rely=0.333, relheight=0.16
				, relwidth=0.703, bordermode='ignore')
		self.txtPdfPath.configure(background="white")
		self.txtPdfPath.configure(font="TkTextFont")
		self.txtPdfPath.configure(foreground="black")
		self.txtPdfPath.configure(highlightbackground="#d9d9d9")
		self.txtPdfPath.configure(highlightcolor="black")
		self.txtPdfPath.configure(insertbackground="black")
		self.txtPdfPath.configure(selectbackground="blue")
		self.txtPdfPath.configure(selectforeground="white")
		self.txtPdfPath.configure(wrap="word")

		self.btChoosePdfFile = tk.Button(self.lfChooseBook)
		self.btChoosePdfFile.place(relx=0.207, rely=0.6, height=34, width=127
				, bordermode='ignore')
		self.btChoosePdfFile.configure(activebackground="#ececec")
		self.btChoosePdfFile.configure(activeforeground="#000000")
		self.btChoosePdfFile.configure(background="#d9d9d9")
		self.btChoosePdfFile.configure(disabledforeground="#a3a3a3")
		self.btChoosePdfFile.configure(foreground="#000000")
		self.btChoosePdfFile.configure(highlightbackground="#d9d9d9")
		self.btChoosePdfFile.configure(highlightcolor="black")
		self.btChoosePdfFile.configure(pady="0")
		self.btChoosePdfFile.configure(text='''Chọn file PDF...''')

		self.lbFilePath = tk.Label(self.lfChooseBook)
		self.lbFilePath.place(relx=0.207, rely=0.133, height=21, width=68
				, bordermode='ignore')
		self.lbFilePath.configure(activebackground="#f9f9f9")
		self.lbFilePath.configure(activeforeground="black")
		self.lbFilePath.configure(background="#d9d9d9")
		self.lbFilePath.configure(disabledforeground="#a3a3a3")
		self.lbFilePath.configure(foreground="#000000")
		self.lbFilePath.configure(highlightbackground="#d9d9d9")
		self.lbFilePath.configure(highlightcolor="black")
		self.lbFilePath.configure(text='''Đường dẫn:''')

		self.FrTotalPageNum = tk.Frame(self.lfChooseBook)
		self.FrTotalPageNum.place(relx=0.526, rely=0.6, relheight=0.3
				, relwidth=0.385, bordermode='ignore')
		self.FrTotalPageNum.configure(relief='groove')
		self.FrTotalPageNum.configure(borderwidth="2")
		self.FrTotalPageNum.configure(relief="groove")
		self.FrTotalPageNum.configure(background="#d9d9d9")
		self.FrTotalPageNum.configure(highlightbackground="#d9d9d9")
		self.FrTotalPageNum.configure(highlightcolor="black")

		self.lbTongSoTrang = tk.Label(self.FrTotalPageNum)
		self.lbTongSoTrang.place(relx=0.049, rely=0.222, height=21, width=82)
		self.lbTongSoTrang.configure(activebackground="#f9f9f9")
		self.lbTongSoTrang.configure(activeforeground="black")
		self.lbTongSoTrang.configure(background="#d9d9d9")
		self.lbTongSoTrang.configure(disabledforeground="#a3a3a3")
		self.lbTongSoTrang.configure(foreground="#000000")
		self.lbTongSoTrang.configure(highlightbackground="#d9d9d9")
		self.lbTongSoTrang.configure(highlightcolor="black")
		self.lbTongSoTrang.configure(text='''Tổng số trang:''')

		self.lbTotalPageNum = tk.Label(self.FrTotalPageNum)
		self.lbTotalPageNum.place(relx=0.488, rely=0.222, height=21, width=72)
		self.lbTotalPageNum.configure(activebackground="#f9f9f9")
		self.lbTotalPageNum.configure(activeforeground="black")
		self.lbTotalPageNum.configure(background="#d9d9d9")
		self.lbTotalPageNum.configure(disabledforeground="#a3a3a3")
		self.lbTotalPageNum.configure(foreground="#000000")
		self.lbTotalPageNum.configure(highlightbackground="#d9d9d9")
		self.lbTotalPageNum.configure(highlightcolor="black")
		self.lbTotalPageNum.configure(text='''0''')

		self.lbPicture1 = tk.Label(self.lfChooseBook)
		self.lbPicture1.place(relx=0.038, rely=0.333, height=71, width=74
				, bordermode='ignore')
		self.lbPicture1.configure(activebackground="#f9f9f9")
		self.lbPicture1.configure(activeforeground="black")
		self.lbPicture1.configure(background="#80ff00")
		self.lbPicture1.configure(disabledforeground="#a3a3a3")
		self.lbPicture1.configure(foreground="#000000")
		self.lbPicture1.configure(highlightbackground="#d9d9d9")
		self.lbPicture1.configure(highlightcolor="black")

		self.lfVoice = tk.LabelFrame(top)
		self.lfVoice.place(relx=0.035, rely=0.679, relheight=0.166
				, relwidth=0.922)
		self.lfVoice.configure(relief='groove')
		self.lfVoice.configure(foreground="black")
		self.lfVoice.configure(text='''Giọng đọc''')
		self.lfVoice.configure(background="#d9d9d9")
		self.lfVoice.configure(highlightbackground="#d9d9d9")
		self.lfVoice.configure(highlightcolor="black")

		self.lfRate = tk.LabelFrame(self.lfVoice)
		self.lfRate.place(relx=0.038, rely=0.174, relheight=0.652, relwidth=0.415
				, bordermode='ignore')
		self.lfRate.configure(relief='groove')
		self.lfRate.configure(foreground="black")
		self.lfRate.configure(text='''Tốc độ''')
		self.lfRate.configure(background="#d9d9d9")
		self.lfRate.configure(highlightbackground="#d9d9d9")
		self.lfRate.configure(highlightcolor="black")

		self.etRate = tk.Entry(self.lfRate)
		self.etRate.place(relx=0.318, rely=0.4, height=20, relwidth=0.382
				, bordermode='ignore')
		self.etRate.configure(background="white")
		self.etRate.configure(disabledforeground="#a3a3a3")
		# self.etRate.configure(font="TkFixedFont")
		self.etRate.configure(foreground="#000000")
		self.etRate.configure(highlightbackground="#d9d9d9")
		self.etRate.configure(highlightcolor="black")
		self.etRate.configure(insertbackground="black")
		self.etRate.configure(selectbackground="blue")
		self.etRate.configure(selectforeground="white")
		self.etRate.configure(textvariable=SachNoi_GUI_support.var_rate)

		self.btRateDown = tk.Button(self.lfRate)
		self.btRateDown.place(relx=0.091, rely=0.4, height=24, width=27
				, bordermode='ignore')
		self.btRateDown.configure(activebackground="#ececec")
		self.btRateDown.configure(activeforeground="#000000")
		self.btRateDown.configure(background="#d9d9d9")
		self.btRateDown.configure(disabledforeground="#a3a3a3")
		self.btRateDown.configure(foreground="#000000")
		self.btRateDown.configure(highlightbackground="#d9d9d9")
		self.btRateDown.configure(highlightcolor="black")
		self.btRateDown.configure(pady="0")
		self.btRateDown.configure(text='''-''')

		self.btRateUp = tk.Button(self.lfRate)
		self.btRateUp.place(relx=0.773, rely=0.4, height=24, width=27
				, bordermode='ignore')
		self.btRateUp.configure(activebackground="#ececec")
		self.btRateUp.configure(activeforeground="#000000")
		self.btRateUp.configure(background="#d9d9d9")
		self.btRateUp.configure(disabledforeground="#a3a3a3")
		self.btRateUp.configure(foreground="#000000")
		self.btRateUp.configure(highlightbackground="#d9d9d9")
		self.btRateUp.configure(highlightcolor="black")
		self.btRateUp.configure(pady="0")
		self.btRateUp.configure(text='''+''')

		self.lfGender = tk.LabelFrame(self.lfVoice)
		self.lfGender.place(relx=0.491, rely=0.174, relheight=0.652
				, relwidth=0.453, bordermode='ignore')
		self.lfGender.configure(relief='groove')
		self.lfGender.configure(foreground="black")
		self.lfGender.configure(text='''Giới tính''')
		self.lfGender.configure(background="#d9d9d9")
		self.lfGender.configure(highlightbackground="#d9d9d9")
		self.lfGender.configure(highlightcolor="black")

		self.rbtMale = tk.Radiobutton(self.lfGender)
		self.rbtMale.place(relx=0.125, rely=0.4, relheight=0.333, relwidth=0.225
				, bordermode='ignore')
		self.rbtMale.configure(activebackground="#ececec")
		self.rbtMale.configure(activeforeground="#000000")
		self.rbtMale.configure(background="#d9d9d9")
		self.rbtMale.configure(disabledforeground="#a3a3a3")
		self.rbtMale.configure(foreground="#000000")
		self.rbtMale.configure(highlightbackground="#d9d9d9")
		self.rbtMale.configure(highlightcolor="black")
		self.rbtMale.configure(justify='left')
		self.rbtMale.configure(text='''Nam''')
		self.rbtMale.configure(value='Male')
		self.rbtMale.configure(variable=SachNoi_GUI_support.selectedGender)

		self.rbtFemale = tk.Radiobutton(self.lfGender)
		self.rbtFemale.place(relx=0.542, rely=0.4, relheight=0.333
				, relwidth=0.183, bordermode='ignore')
		self.rbtFemale.configure(activebackground="#ececec")
		self.rbtFemale.configure(activeforeground="#000000")
		self.rbtFemale.configure(background="#d9d9d9")
		self.rbtFemale.configure(disabledforeground="#a3a3a3")
		self.rbtFemale.configure(foreground="#000000")
		self.rbtFemale.configure(highlightbackground="#d9d9d9")
		self.rbtFemale.configure(highlightcolor="black")
		self.rbtFemale.configure(justify='left')
		self.rbtFemale.configure(text='''Nữ''')
		self.rbtFemale.configure(value='Female')
		self.rbtFemale.configure(variable=SachNoi_GUI_support.selectedGender)

		self.frButtons = tk.Frame(top)
		self.frButtons.place(relx=0.035, rely=0.867, relheight=0.079
				, relwidth=0.93)
		self.frButtons.configure(relief='groove')
		self.frButtons.configure(borderwidth="2")
		self.frButtons.configure(relief="groove")
		self.frButtons.configure(background="#d9d9d9")
		self.frButtons.configure(highlightbackground="#d9d9d9")
		self.frButtons.configure(highlightcolor="black")

		self.lbCurrentPage = tk.Label(self.frButtons)
		self.lbCurrentPage.place(relx=0.037, rely=0.182, height=31, width=171)
		self.lbCurrentPage.configure(activebackground="#f9f9f9")
		self.lbCurrentPage.configure(activeforeground="black")
		self.lbCurrentPage.configure(background="#d9d9d9")
		self.lbCurrentPage.configure(disabledforeground="#a3a3a3")
		self.lbCurrentPage.configure(foreground="#000000")
		self.lbCurrentPage.configure(highlightbackground="#d9d9d9")
		self.lbCurrentPage.configure(highlightcolor="black")
		self.lbCurrentPage.configure(text='''Đang đọc trang: 0/0''')

		self.btReadBook = tk.Button(self.frButtons)
		self.btReadBook.place(relx=0.374, rely=0.182, height=34, width=87)
		self.btReadBook.configure(activebackground="#ececec")
		self.btReadBook.configure(activeforeground="#000000")
		self.btReadBook.configure(background="#d9d9d9")
		self.btReadBook.configure(disabledforeground="#a3a3a3")
		self.btReadBook.configure(foreground="#000000")
		self.btReadBook.configure(highlightbackground="#d9d9d9")
		self.btReadBook.configure(highlightcolor="black")
		self.btReadBook.configure(pady="0")
		self.btReadBook.configure(text='''Đọc sách''')

		self.btViewBook = tk.Button(self.frButtons)
		self.btViewBook.place(relx=0.561, rely=0.182, height=34, width=87)
		self.btViewBook.configure(activebackground="#ececec")
		self.btViewBook.configure(activeforeground="#000000")
		self.btViewBook.configure(background="#d9d9d9")
		self.btViewBook.configure(disabledforeground="#a3a3a3")
		self.btViewBook.configure(foreground="#000000")
		self.btViewBook.configure(highlightbackground="#d9d9d9")
		self.btViewBook.configure(highlightcolor="black")
		self.btViewBook.configure(pady="0")
		self.btViewBook.configure(text='''Xem sách''')

		self.btExit = tk.Button(self.frButtons)
		self.btExit.place(relx=0.748, rely=0.182, height=34, width=87)
		self.btExit.configure(activebackground="#ececec")
		self.btExit.configure(activeforeground="#000000")
		self.btExit.configure(background="#d9d9d9")
		self.btExit.configure(disabledforeground="#a3a3a3")
		self.btExit.configure(foreground="#000000")
		self.btExit.configure(highlightbackground="#d9d9d9")
		self.btExit.configure(highlightcolor="black")
		self.btExit.configure(pady="0")
		self.btExit.configure(text='''Thoát''')

		# Bổ sung
		self.top = top
		self.addtion()

	# Bổ sung
	def addtion(self):
		# Chung
		self.top.iconbitmap('audio-book-headphone.ico')
		self.top.protocol("WM_DELETE_WINDOW", self.on_closing)
		self.btImages = {
			'pdf': tk.PhotoImage(file='images/clipart1529911.png').subsample(20, 20),
			'view_book': tk.PhotoImage(file='images/pngaaa.com-1142508.png').subsample(120, 120),
			'read_book': tk.PhotoImage(file='images/SeekPng.com_ps3-logo-png_1776687.png').subsample(20, 20),
			'view_book': tk.PhotoImage(file='images/pngaaa.com-1142508.png').subsample(120, 120),
			'exit_program': tk.PhotoImage(file='images/clipart1198492.png').subsample(30, 30)
		}
		self.add_images()
		self.book = None

		# Chọn sách
		self.txtPdfPath.bind("<Key>", lambda e: window.ctrlEvent(e))
		self.file_path = ''
		self.btChoosePdfFile.config(image=self.btImages['pdf'], compound='left', command=self.choosePdfFile)

		# Chế độ đọc
		self.cbOnePage.config(state='readonly')
		self.cbMultiPagesFrom.config(state='readonly')
		self.cbMultiPagesFrom.bind('<<ComboboxSelected>>', self.changeToPage)
		self.cbMultiPagesTo.config(state='readonly')

		# Giọng đọc
		self.engine = pyttsx3.init()
		self.etRate.config(justify='center', state='readonly')
		SachNoi_GUI_support.var_rate.set(self.engine.getProperty('rate'))
		self.btRateDown.config(command=self.rate_down)
		self.btRateUp.config(command=self.rate_up)

		# Các nút
		self.btReadBook.config(image=self.btImages['read_book'], compound='left', command=self.read_book, )
		self.btViewBook.config(image=self.btImages['view_book'], compound='left', command=self.view_book, )
		self.btExit.config(image=self.btImages['exit_program'], compound='left', command=self.exit_program, )

		self.load_settings()

	# Giảm tốc độ
	def rate_down(self):
		value = SachNoi_GUI_support.var_rate.get()
		if value - 10 > 0:
			SachNoi_GUI_support.var_rate.set(value - 10)

	# Tăng tốc độ
	def rate_up(self):
		value = SachNoi_GUI_support.var_rate.get()
		if value + 10 < 1000:
			SachNoi_GUI_support.var_rate.set(value + 10)

	@staticmethod
	def ctrlEvent(event):
		if(event.state == 12 and event.keysym in ('a', 'c', 'x', 'v')):
			return
		else:
			return "break"

	# Sửa lại đến số trang
	def changeToPage(self, event):
		fromPage = int(self.cbMultiPagesFrom.get())
		toPage = int(self.cbMultiPagesTo.get())
		self.cbMultiPagesTo.config(value=list(range(fromPage, self.book.numPages+1)))
		if fromPage > toPage:
			self.cbMultiPagesTo.set(fromPage)

	# Thêm hình ảnh
	def add_images(self):
		self.images = [
			ImageTk.PhotoImage(Image.open('images/icons8-audio-book-80.png').resize((50, 50), Image.ANTIALIAS)),
			ImageTk.PhotoImage(Image.open('images/audio-book.png').resize((50, 50), Image.ANTIALIAS)),
			ImageTk.PhotoImage(Image.open('images/audio-book (2).png').resize((50, 50), Image.ANTIALIAS))
		]
		self.pictures = [
			self.lbPicture1,
			self.lbPicture2,
			self.lbPicture3,
		]
		for i in range(3):
			self.pictures[i].config(image=self.images[i], background='#d9d9d9')

	# Chọn file
	def choosePdfFile(self):
		filetypes = (
			('PDF files', '*.pdf'),
		)
		self.file_path = fd.askopenfilename(
			title='Chọn sách',
			filetypes=filetypes)

		if self.file_path != '':
			self.txtPdfPath.delete(1.0, tk.END)
			self.txtPdfPath.insert(1.0, self.file_path)
			self.readPdfFile()

	# Đọc dữ liệu tệp PDF từ máy tính
	def readPdfFile(self):
		pdfFile = open(self.file_path, 'rb')
		self.book = PyPDF2.PdfFileReader(pdfFile)
		self.lbTotalPageNum.config(text=self.book.numPages)

		self.cbOnePage.config(value=list(range(1, self.book.numPages+1)))
		self.cbOnePage.current(0)
		self.cbMultiPagesFrom.config(value=list(range(1, self.book.numPages+1)))
		self.cbMultiPagesFrom.current(0)
		self.cbMultiPagesTo.config(value=list(range(1, self.book.numPages+1)))
		self.cbMultiPagesTo.set(self.book.numPages)

	# Đọc sách
	def read_book(self):
		if self.book == None:
			mb.showerror('Lỗi', 'Bạn chưa chọn sách cần đọc!')
			return
		
		# Giọng đọc
		rate = SachNoi_GUI_support.var_rate.get()
		self.engine.setProperty('rate', rate)
		gender = SachNoi_GUI_support.selectedGender.get()
		if gender == 'Male':
			self.engine.setProperty('voice', self.engine.getProperty('voices')[0].id)
		elif gender == 'Female':
			self.engine.setProperty('voice', self.engine.getProperty('voices')[1].id)
		
		# Chế độ đọc
		seletedMode = SachNoi_GUI_support.selectedMode.get()
		# Đọc tất cả
		if seletedMode == 0:
			threading._start_new_thread(self.read_multiple_pages, (1, self.book.numPages))
		# Đọc 1 trang
		elif seletedMode == 1:
			page = int(self.cbOnePage.get())
			threading._start_new_thread(self.read_multiple_pages, (page, page))
		# Đọc nhiều trang:
		elif seletedMode == 2:
			fromPage = int(self.cbMultiPagesFrom.get())
			toPage = int(self.cbMultiPagesTo.get())
			threading._start_new_thread(self.read_multiple_pages, (fromPage, toPage))

	# Đọc nhiều trang (dùng cho cả 3 trường hợp)
	def read_multiple_pages(self, fromPage, toPage):
		try:
			for i in range(fromPage - 1, toPage):
				self.lbCurrentPage.config(text=f'Đang đọc trang: {i+1}/{self.book.numPages}')
				page = self.book.getPage(i)
				text = page.extractText().replace('\n', ' ')
				self.engine.say(text)
				self.engine.runAndWait()
			self.lbCurrentPage.config(text='Đang đọc trang: 0/0')
		except:
			mb.showerror('Lỗi', 'Không thể thực hiện thao tác này khi có sách đang được đọc!')

	# Xem sách
	def view_book(self):
		if self.file_path != '':
			os.startfile(self.file_path)
		else:
			mb.showerror('Lỗi', 'Bạn chưa chọn sách cần đọc!')

	# Thoát
	def exit_program(self):
		self.on_closing()

	def on_closing(self):
		if mb.askokcancel('Thoát', "Bạn có chắc muốn thoát ứng dụng không"):
			self.save_settings()
			self.top.destroy()

	# Lưu cài đặt
	def save_settings(self):
		# Chế độ đọc
		seletedMode = SachNoi_GUI_support.selectedMode.get()
		page = int(self.cbOnePage.get())
		fromPage = int(self.cbMultiPagesFrom.get())
		toPage = int(self.cbMultiPagesTo.get())

		# Giọng đọc
		rate = SachNoi_GUI_support.var_rate.get()
		gender = SachNoi_GUI_support.selectedGender.get()

		settings = [
			f'file_path={self.file_path}\n',
			f'read_mode={seletedMode}\n',
			f'page={page}\n',
			f'fromPage={fromPage}\n',
			f'toPage={toPage}\n',
			f'rate={rate}\n',
			f'gender={gender}\n'
		]
		with open('settings.txt', 'w') as file:
			file.writelines(settings)

	# Tải lại cài đặt
	def load_settings(self):
		settings = []
		try:
			with open('settings.txt', 'r') as file:
				settings = file.readlines()
			for s in settings:
				key, value = s.strip().split('=')
				if key == 'file_path':
					self.file_path = value
					self.txtPdfPath.insert(1.0, self.file_path)
					self.readPdfFile()
				elif key == 'read_mode':
					mode = int(value)
					if mode in (0, 1, 2):
						SachNoi_GUI_support.selectedMode.set(value)
				elif key == 'page' and self.file_path != '':
					page = int(value)
					if 1 <= page <= self.book.numPages:
						self.cbOnePage.set(page)
				elif key == 'fromPage' and self.file_path != '':
					fromPage = int(value)
					if 1 <= fromPage <= self.book.numPages:
						self.cbMultiPagesFrom.set(fromPage)
				elif key == 'toPage' and self.file_path != '':
					fromPage = int(self.cbMultiPagesFrom.get())
					toPage = int(value)
					if 1 <= toPage <= self.book.numPages:
						self.cbMultiPagesTo.set(toPage)
				elif key == 'rate':
					rate = int(value)
					if 10 <= rate <= 1000:
						SachNoi_GUI_support.var_rate.set(value)
				elif key == 'gender':
					if value in ('Male', 'Female'):
						SachNoi_GUI_support.selectedGender.set(value)
		except:
			self.set_default_settings()

	def set_default_settings(self):
		self.file_path = ''
		self.book = None
		self.txtPdfPath.delete(1.0, tk.END)
		self.lbTotalPageNum.config(text='0')
		SachNoi_GUI_support.selectedMode.set(0)
		SachNoi_GUI_support.var_cbOnePage.set(0)
		SachNoi_GUI_support.var_cbMultiPagesFrom.set(0)
		SachNoi_GUI_support.var_cbMultiPagesTo.set(0)
		SachNoi_GUI_support.var_rate.set(200)
		SachNoi_GUI_support.selectedGender.set('Male')

if __name__ == '__main__':
	vp_start_gui()