#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jul 22, 2021 05:43:01 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 575x692+485+40
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Sách nói"
    vTcl:DefineAlias "$top" "window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        -foreground black -text {Chế độ đọc} -background $vTcl(actual_gui_bg) \
        -height 286 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 530 
    vTcl:DefineAlias "$top.lab46" "lfReadMode" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab46
    frame $site_3_0.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 85 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 385 
    vTcl:DefineAlias "$site_3_0.fra54" "Frame1" vTcl:WidgetProc "window" 1
    set site_4_0 $site_3_0.fra54
    radiobutton $site_4_0.rad55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Đọc một trang:} -value 1 
    vTcl:DefineAlias "$site_4_0.rad55" "rbtReadOnePage" vTcl:WidgetProc "window" 1
    label $site_4_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Số trang:} 
    vTcl:DefineAlias "$site_4_0.lab56" "lbSoTrang" vTcl:WidgetProc "window" 1
    ttk::combobox $site_4_0.tCo57 \
        -textvariable var_cbOnePage -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo57" "cbOnePage" vTcl:WidgetProc "window" 1
    place $site_4_0.rad55 \
        -in $site_4_0 -x 10 -y 10 -width 108 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 30 -y 40 -width 53 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo57 \
        -in $site_4_0 -x 90 -y 40 -width 83 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra58 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 105 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 385 
    vTcl:DefineAlias "$site_3_0.fra58" "Frame2" vTcl:WidgetProc "window" 1
    set site_4_0 $site_3_0.fra58
    radiobutton $site_4_0.rad59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Đọc nhiều trang:} -value 2 
    vTcl:DefineAlias "$site_4_0.rad59" "rbtReadMultiPages" vTcl:WidgetProc "window" 1
    label $site_4_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Từ trang:} 
    vTcl:DefineAlias "$site_4_0.lab45" "lbTuTrang" vTcl:WidgetProc "window" 1
    ttk::combobox $site_4_0.tCo46 \
        -textvariable var_cbMultiPagesFrom -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo46" "cbMultiPagesFrom" vTcl:WidgetProc "window" 1
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Đến trang:} 
    vTcl:DefineAlias "$site_4_0.lab46" "lbDenTrang" vTcl:WidgetProc "window" 1
    ttk::combobox $site_4_0.tCo47 \
        -textvariable var_cbMultiPagesTo -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo47" "cbMultiPagesTo" vTcl:WidgetProc "window" 1
    place $site_4_0.rad59 \
        -in $site_4_0 -x 10 -y 10 -width 116 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 30 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.tCo46 \
        -in $site_4_0 -x 90 -y 50 -width 83 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 210 -y 50 -width 53 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo47 \
        -in $site_4_0 -x 270 -y 50 -width 83 -height 21 -anchor nw \
        -bordermode ignore 
    radiobutton $site_3_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Đọc tất cả} -value 0 
    vTcl:DefineAlias "$site_3_0.rad48" "rbtReadAll" vTcl:WidgetProc "window" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #80ff00 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab52" "lbPicture2" vTcl:WidgetProc "window" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #80ff00 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab54" "lbPicture3" vTcl:WidgetProc "window" 1
    place $site_3_0.fra54 \
        -in $site_3_0 -x 20 -y 60 -width 385 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra58 \
        -in $site_3_0 -x 20 -y 160 -width 385 -relwidth 0 -height 105 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad48 \
        -in $site_3_0 -x 30 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 430 -y 70 -width 64 -relwidth 0 -height 61 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 430 -y 180 -width 64 -height 61 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab52 \
        -foreground black -text {Chọn sách} -background $vTcl(actual_gui_bg) \
        -height 150 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 532 
    vTcl:DefineAlias "$top.lab52" "lfChooseBook" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab52
    text $site_3_0.tex54 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 374 -wrap word 
    $site_3_0.tex54 configure -font "TkTextFont"
    $site_3_0.tex54 insert end text
    vTcl:DefineAlias "$site_3_0.tex54" "txtPdfPath" vTcl:WidgetProc "window" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Chọn file PDF...} 
    vTcl:DefineAlias "$site_3_0.but55" "btChoosePdfFile" vTcl:WidgetProc "window" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Đường dẫn:} 
    vTcl:DefineAlias "$site_3_0.lab47" "lbFilePath" vTcl:WidgetProc "window" 1
    frame $site_3_0.fra60 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 45 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 205 
    vTcl:DefineAlias "$site_3_0.fra60" "FrTotalPageNum" vTcl:WidgetProc "window" 1
    set site_4_0 $site_3_0.fra60
    label $site_4_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Tổng số trang:} 
    vTcl:DefineAlias "$site_4_0.lab61" "lbTongSoTrang" vTcl:WidgetProc "window" 1
    label $site_4_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0 
    vTcl:DefineAlias "$site_4_0.lab62" "lbTotalPageNum" vTcl:WidgetProc "window" 1
    place $site_4_0.lab61 \
        -in $site_4_0 -x 10 -y 10 -width 82 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 100 -y 10 -width 72 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #80ff00 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.lab63" "lbPicture1" vTcl:WidgetProc "window" 1
    place $site_3_0.tex54 \
        -in $site_3_0 -x 110 -y 50 -width 374 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 110 -y 90 -width 127 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 110 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.fra60 \
        -in $site_3_0 -x 280 -y 90 -width 205 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 20 -y 50 -width 74 -relwidth 0 -height 71 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab49 \
        -foreground black -text {Giọng đọc} -background $vTcl(actual_gui_bg) \
        -height 115 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 530 
    vTcl:DefineAlias "$top.lab49" "lfVoice" vTcl:WidgetProc "window" 1
    set site_3_0 $top.lab49
    labelframe $site_3_0.lab50 \
        -foreground black -text {Tốc độ} -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 220 
    vTcl:DefineAlias "$site_3_0.lab50" "lfRate" vTcl:WidgetProc "window" 1
    set site_4_0 $site_3_0.lab50
    entry $site_4_0.ent45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable tvarRate -width 84 
    vTcl:DefineAlias "$site_4_0.ent45" "etRate" vTcl:WidgetProc "window" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$site_4_0.but46" "btRateDown" vTcl:WidgetProc "window" 1
    button $site_4_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$site_4_0.but47" "btRateUp" vTcl:WidgetProc "window" 1
    place $site_4_0.ent45 \
        -in $site_4_0 -x 70 -y 30 -width 84 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 20 -y 30 -width 27 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but47 \
        -in $site_4_0 -x 170 -y 30 -width 27 -height 24 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab45 \
        -foreground black -text {Giới tính} -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_3_0.lab45" "lfGender" vTcl:WidgetProc "window" 1
    set site_4_0 $site_3_0.lab45
    radiobutton $site_4_0.rad48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Nam -value 'Male' -variable selectedGender 
    vTcl:DefineAlias "$site_4_0.rad48" "rbtMale" vTcl:WidgetProc "window" 1
    radiobutton $site_4_0.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Nữ -value 'Female' -variable selectedGender 
    vTcl:DefineAlias "$site_4_0.rad50" "rbtFemale" vTcl:WidgetProc "window" 1
    place $site_4_0.rad48 \
        -in $site_4_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.rad50 \
        -in $site_4_0 -x 130 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 20 -y 20 -width 220 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 260 -y 20 -width 240 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 535 
    vTcl:DefineAlias "$top.fra48" "frButtons" vTcl:WidgetProc "window" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Đang đọc trang: 0/0} 
    vTcl:DefineAlias "$site_3_0.lab57" "lbCurrentPage" vTcl:WidgetProc "window" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Đọc sách} 
    vTcl:DefineAlias "$site_3_0.but51" "btReadBook" vTcl:WidgetProc "window" 1
    button $site_3_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Xem sách} 
    vTcl:DefineAlias "$site_3_0.but45" "btViewBook" vTcl:WidgetProc "window" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Thoát 
    vTcl:DefineAlias "$site_3_0.but46" "btExit" vTcl:WidgetProc "window" 1
    place $site_3_0.lab57 \
        -in $site_3_0 -x 20 -y 10 -width 171 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 200 -y 10 -width 87 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 300 -y 10 -width 87 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 400 -y 10 -width 87 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 20 -y 170 -width 530 -relwidth 0 -height 286 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 20 -y 10 -width 532 -relwidth 0 -height 150 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 20 -y 470 -width 530 -relwidth 0 -height 115 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 20 -y 600 -width 535 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

